"use client";
import { useEffect, useMemo, useState } from "react";
type DeckSlide = { kicker: string; label: string; title: string; desc?: string; kind: "cover" | "cards" | "chain" | "matrix" | "route" | "code" | "end"; items?: string[][]; blocks?: string[][]; note?: string };
const agentSlides: DeckSlide[] = [
  { kind: "cover", kicker: "PART I / CODING AGENTS", label: "AI 编程 Agent 观察", title: "Coding Agent\n不是排名，而是分工。", desc: "Cursor · Codex · OpenCode · DeepSeek Harness · Pi" },
  { kind: "cards", kicker: "01 / POINT OF VIEW", label: "先讲结论", title: "Agent 越来越多，\n选择却不该更复杂。", desc: "真正重要的问题不是哪个最好，而是哪个适合日常，哪个扛复杂任务，哪个值得拿来改造。", items: [["01", "按工作流分工", "不同 Agent 解决不同问题"], ["02", "按真实任务验证", "不被演示和榜单带着走"], ["03", "按组合而非单挑", "主力、备选、实验室各就各位"]] },
  { kind: "chain", kicker: "02 / THE LANDSCAPE", label: "五种流派", title: "先把地图\n画出来。", desc: "IDE、CLI、云端平台和 Harness 不应该被放进同一张谁更强的榜单。", items: [["01", "IDE 原生型", "Cursor / Copilot", "每天都在身边"], ["02", "终端 Agent 型", "Codex / OpenCode", "命令驱动复杂任务"], ["03", "云端异步型", "Cloud Agent / Devin", "交给后台跑"], ["04", "可编程 Harness", "Pi / DeepSeek Harness", "自己定义 Agent"], ["05", "应用生成型", "Replit / Bolt", "从想法到原型"]] },
  { kind: "matrix", kicker: "03 / THE FOUR", label: "四个主角", title: "四个工具，\n四种答案。", desc: "你的组合已经覆盖个人开发者最重要的使用面。", items: [["Cursor", "IDE 原生 / 日常主力", "顺手，连续，低门槛"], ["Codex", "生态型 / 复杂任务", "综合能力，长任务"], ["OpenCode", "开源 / 备用通道", "低成本，能切换"], ["DeepSeek Harness", "Harness / 深度定制", "插件化，适合折腾"]] },
  { kind: "route", kicker: "04 / RECOMMENDED STACK", label: "建议组合", title: "不是全都要，\n而是各就各位。", desc: "一套好用的 Agent 组合，应该像一支研发团队：角色不同，但协作清楚。", items: [["01", "日常开发", "Cursor", "稳定、顺手、低门槛"], ["02", "复杂任务", "Codex", "全仓库、多步骤、长任务"], ["03", "备用通道", "OpenCode", "开源、低成本、可切换"], ["04", "研究定制", "DeepSeek Harness", "源码、插件、工作流"]] },
  { kind: "end", kicker: "05 / FROM TOOLS TO WORKFLOWS", label: "技能与场景", title: "工具之外，\n还有工作流。", desc: "OpenAI Use Cases 展示了把一次次对话沉淀成可复用技能的路径。", items: [["理解", "Understand large codebases", "梳理大型代码库和请求链路"], ["验证", "Review pull requests", "提前发现回归和潜在问题"], ["自动化", "Run verified operations", "重复执行并留下验证结果"], ["沉淀", "Save workflows as skills", "把成熟流程保存成团队能力"]], note: "真实任务 > 演示效果" }
];
const docsSlides: DeckSlide[] = [
  { kind: "cover", kicker: "PART II / AI PROJECT DOCS", label: "AI 项目文档入口", title: "AI 接手项目，\n先看文档入口。", desc: "真实目录结构 · 真实 Markdown · 逐项讲解" },
  { kind: "cards", kicker: "06 / WHY AN ENTRY POINT", label: "为什么需要入口文档", title: "没有入口，\nAI 会先搞错。", desc: "旧项目往往同时包含现状、历史分析和未来规划。入口文档先把事实和边界讲清楚。", items: [["可能混淆", "Symfony 与 Laravel", "把迁移目标误当成当前实现"], ["可能混淆", "Web / H5 / App / Agent", "多套认证入口，不能套用同一规则"], ["可能混淆", "不同接口响应格式", "旧系统的响应并不统一"], ["入口价值", "先确认，再动代码", "知道读什么、改什么、如何验证"]] },
  { kind: "chain", kicker: "07 / THE DOCUMENT CHAIN", label: "四类资料的关系", title: "四类资料，\n一条导航链。", desc: "不是四份重复说明，而是从兼容入口到正式交付的不同层级。", items: [["01", "AGENTS.md", "兼容入口", "告诉所有 AI 从哪里开始"], ["02", "CLAUDE.md", "项目主规则", "现状、环境、架构和铁律"], ["03", ".claude/", "本地分析库", "清单、风险、上下文和日志"], ["04", "docs/", "正式交付", "需求、测试和部署"]] },
  { kind: "code", kicker: "08 / THE FIRST TWO FILES", label: "入口文件", title: "短入口，\n长上下文。", desc: "入口文件不承担所有细节，只负责把 AI 引导到正确的位置。", blocks: [["AGENTS.md", "# AI 接手入口\n\n统一阅读 CLAUDE.md\n不要全量扫描代码库\n当前是 Symfony 3.3\n改接口前先读风险分析"], ["CLAUDE.md", "# 项目定位\n图书、作业、考试、教师端\n\n## 环境速查\nPHP 5.6.9\nSymfony 3.3.14\nDoctrine ORM"]] },
  { kind: "matrix", kicker: "09 / CURRENT CODE FACTS", label: "项目现状", title: "环境事实，\n决定 AI 怎么写。", desc: "版本、命令和依赖边界，是生成代码和验证方案的前提。", items: [["PHP 5.6.9", "语言 / 版本", "语法必须兼容旧版本"], ["Symfony 3.3.14", "框架", "命令入口是 php bin/console"], ["Doctrine ORM", "数据层", "不能默认套用其它项目习惯"], ["先读文档", "注意事项", "不要默认全量扫描"]] },
  { kind: "route", kicker: "10 / THE HANDOFF LOOP", label: "新任务接手流程", title: "新任务接手，\n按四步收口。", desc: "从入口规则到专题知识，再回到代码和验证，最后把结论留在知识库里。", items: [["01", "读入口", "AGENTS.md / CLAUDE.md", "确认现状和禁区"], ["02", "选专题", ".claude/ 清单、风险和历史", "按任务读取上下文"], ["03", "定位代码", "路由 → Controller → Service", "回到真实实现"], ["04", "验证留痕", "命令、Diff、测试与日志", "把结论留下来"]] },
  { kind: "end", kicker: "11 / QUICK REFERENCE", label: "一页速查", title: "先建立事实，\n再让 AI 动手。", desc: "文档不是 AI 的附属品，而是 AI 进入真实项目时的第一层工程基础设施。", items: [["AGENTS.md", "入口在哪里", "哪些提醒必须先看到"], ["CLAUDE.md", "当前项目是什么", "环境、架构和铁律是什么"], [".claude/", "专题材料在哪里", "接口、风险、规划和历史"], ["docs/", "交付资料在哪里", "需求、测试、部署与团队交付"]] }
];
function Title({ slide }: { slide: DeckSlide }) { const lines = slide.title.split("\n"); return <div className="unified-heading"><div><h1>{lines.map((line, index) => <span key={line}>{index > 0 && <br />}<em className={index === lines.length - 1 ? "accent" : ""}>{line}</em></span>)}</h1>{slide.desc && <p>{slide.desc}</p>}</div></div>; }
function SlideBody({ slide }: { slide: DeckSlide }) {
  if (slide.kind === "cover") return <><div className="unified-kicker"><span className="orange-dot" /> {slide.kicker}</div><Title slide={slide} /><div className="cover-graphic"><div>PROJECT<br /><b>MAP</b></div><span>MODEL</span><span>TOOLS</span><span>CONTEXT</span><span>WORKFLOW</span></div><div className="unified-footer"><span>{slide.desc}</span><span>← / → 开始浏览</span></div></>;
  return <><div className="unified-topline"><span>{slide.kicker}</span><span>{slide.label}</span></div><Title slide={slide} />{slide.kind === "cards" && <div className="content-cards">{slide.items?.map(([tag, name, text]) => <article key={name}><span>{tag}</span><strong>{name}</strong><p>{text}</p></article>)}</div>}{slide.kind === "chain" && <div className="content-chain">{slide.items?.map(([number, name, role, text]) => <article key={name}><b>{number}</b><strong>{name}</strong><span>{role}</span><p>{text}</p></article>)}</div>}{slide.kind === "matrix" && <div className="content-matrix"><div className="matrix-head"><span>工具 / 事实</span><span>定位</span><span>说明</span></div>{slide.items?.map(([name, role, text]) => <div key={name}><strong>{name}</strong><b>{role}</b><span>{text}</span></div>)}</div>}{slide.kind === "route" && <div className="content-route">{slide.items?.map(([number, name, main, text]) => <div key={number}><b>{number}</b><strong>{name}</strong><span>{main}</span><small>{text}</small></div>)}</div>}{slide.kind === "code" && <div className="content-code">{slide.blocks?.map(([name, text]) => <article key={name}><span>{name}</span><pre>{text}</pre></article>)}</div>}{slide.kind === "end" && <><div className="content-cards end-cards">{slide.items?.map(([name, role, text]) => <article key={name}><span>{name}</span><strong>{role}</strong><p>{text}</p></article>)}</div><div className="end-note">{slide.note || "内容收口 / 先建立当前事实，再按任务取上下文。"}</div></>}</>;
}
export default function Home() {
  const [section, setSection] = useState<"agent" | "docs">("agent");
  const [active, setActive] = useState(0);
  const slides = useMemo(() => section === "agent" ? agentSlides : docsSlides, [section]);
  const slide = slides[active];
  const go = (delta: number) => setActive((value) => Math.max(0, Math.min(slides.length - 1, value + delta)));
  const switchSection = (next: "agent" | "docs") => { setSection(next); setActive(0); };
  useEffect(() => { const onKey = (event: KeyboardEvent) => { if (["ArrowRight", "ArrowDown", "PageDown", " "].includes(event.key)) { event.preventDefault(); go(1); } if (["ArrowLeft", "ArrowUp", "PageUp"].includes(event.key)) { event.preventDefault(); go(-1); } if (event.key === "Home") setActive(0); if (event.key === "End") setActive(slides.length - 1); }; window.addEventListener("keydown", onKey); return () => window.removeEventListener("keydown", onKey); }, [slides.length]);
  return <main className={`unified-app ${slide.kind}`}><header className="unified-bar"><a className="unified-brand" href="#slide-1"><span>AI</span><b>项目分享</b></a><nav className="section-nav"><button className={section === "agent" ? "active" : ""} onClick={() => switchSection("agent")}>01 / AI 编程 Agent</button><button className={section === "docs" ? "active" : ""} onClick={() => switchSection("docs")}>02 / 项目文档入口</button></nav><div className="unified-counter"><span>{String(active + 1).padStart(2, "0")}</span><i>/</i>{String(slides.length).padStart(2, "0")}</div></header><section className="unified-stage"><div className="unified-slide"><SlideBody slide={slide} /></div></section><footer className="unified-controls"><div className="progress-track"><span style={{ width: `${((active + 1) / slides.length) * 100}%` }} /></div><div className="dot-nav">{slides.map((_, index) => <button key={index} className={active === index ? "active" : ""} onClick={() => setActive(index)} aria-label={`第 ${index + 1} 页`} />)}</div><div className="nav-buttons"><button onClick={() => go(-1)} disabled={active === 0} aria-label="上一页">←</button><button onClick={() => go(1)} disabled={active === slides.length - 1} aria-label="下一页">→</button></div></footer></main>;
}
