"use client";
import { useEffect, useMemo, useState } from "react";
import { documentSlides } from "./document-slides";
type DeckSlide = { kicker: string; label: string; title: string; desc?: string; footer?: string; url?: string; kind: "cover" | "intro" | "usecases" | "compare" | "cards" | "chain" | "matrix" | "route" | "code" | "facts" | "list" | "track" | "end"; items?: string[][]; blocks?: string[][]; cards?: string[][]; left?: { title: string; items: string[] }; right?: { title: string; items: string[] }; note?: string };
const agentSlides: DeckSlide[] = [
  { kind: "intro", kicker: "AI CODING / SHARING", label: "分享介绍", title: "AI 编程实践分享。\n从工具到落地。", desc: "实际使用的 Coding Agent、Agent 架构，以及 AI 如何接手真实项目。", footer: "时间 / 地点：下午 3:00–4:00  ·  第四会议室", items: [["分享人", "曹宇春 · 谢洋", "两个人一起分享工具实践与项目落地"], ["PART I", "Agent 工具与架构", "Cursor · Codex · OpenCode · DeepSeek Harness · Pi；日常编码、复杂任务、多模态与 Agent 内部组成"], ["PART II", "AI 如何接手真实项目", "先读规则、上下文和专题资料，再开始改代码"], ["适合谁", "产品、研发与技术管理者", "了解工具差异，建立自己的 AI 编程工作流"]] },
  { kind: "cover", kicker: "PART I / MY CODING AGENTS", label: "我的 Agent 工具栈", title: "我的 Coding Agent\n工具栈与架构。", desc: "Cursor · Codex · OpenCode · DeepSeek Harness · Pi / Model · Harness · Tools · Context" },
  { kind: "cards", kicker: "01 / MY DAILY STACK", label: "我为什么用多个 Agent", title: "不是重复采购，\n而是不同角色。", desc: "我实际使用的几个 Agent，分别覆盖日常编码、复杂任务、备用通道和 Agent 工程。", items: [["01", "日常主力", "Cursor：编辑器里顺手完成连续开发"], ["02", "复杂任务", "Codex：GPT 与 Coding Agent 合并后的全能型 Agent；适合多步骤、全仓库和长任务"], ["03", "备用通道", "OpenCode：开箱即用，成本友好，可切换"], ["04", "Agent 工程", "DeepSeek Harness / Pi：理解和改造 Agent 内部组成，Agent 工程师必备"]] },
  { kind: "chain", kicker: "02 / MY AGENT MAP", label: "我使用的 Agent", title: "先看工具，\n再看它们怎么协作。", desc: "每个工具都不是孤立的，真正的组合是：主力开发 + 全能 Agent + 备用能力 + 实验室。", items: [["01", "Cursor", "IDE 原生", "日常编码和快速迭代"], ["02", "Codex", "GPT × Coding Agent", "对话、Site、远程控制、图片生成，以及全仓库长任务"], ["03", "OpenCode", "开源通道", "低成本备选和模型切换"], ["04", "DeepSeek Harness", "可改造平台", "插件、上下文和 Agent Loop"], ["05", "Pi", "极简工具箱", "用积木理解 Agent"]] },
  { kind: "cards", kicker: "03 / GPT × CODEX", label: "全能型能力", title: "不是只会写代码，\n而是完整的工作入口。", desc: "我用 Codex 比较多的原因，是 GPT 的对话能力和 Coding Agent 能力合在了一起。", items: [["01", "语音协作", "像和同事一样连续讨论问题、追问和确认"], ["02", "GPT Site", "从一句需求生成可预览、可修改、可部署的网站"], ["03", "Remote Control", "让 Agent 操作电脑、浏览页面并验证结果"], ["04", "图片设计", "把产品想法先变成视觉草图、UI 方案和原型方向"]] },
  { kind: "chain", kicker: "04 / VOICE COLLABORATION", label: "语音功能", title: "从打字交互，\n变成实时协作。", desc: "它不只是把文字读出来，而是可以像和同事交流一样持续沟通。", items: [["01", "自然对话", "直接说目标", "不必先整理成命令"], ["02", "连续上下文", "追问和补充", "可以随时调整方向"], ["03", "任务跟进", "布置和询问", "讨论进度与结果"], ["04", "人工收口", "最后确认", "高风险操作仍由人决定"]] },
  { kind: "route", kicker: "05 / GPT SITES", label: "GPT Site 建站", title: "从一个想法，\n到一个能用的网站。", desc: "描述需求，生成预览，持续修改，最后发布分享；适合内部页面、看板、报告和轻量应用。", url: "https://chatgpt.com/sites", items: [["01", "描述需求", "对象、内容、风格和功能", "先把想法说清楚"], ["02", "生成预览", "网站或轻量应用", "马上看到结果"], ["03", "持续修改", "布局、内容和交互", "边看边改"], ["04", "发布分享", "生成站点地址", "从原型走向交付"]] },
  { kind: "cards", kicker: "06 / GPT IMAGE FOR DESIGN", label: "产品设计", title: "先把想法看见，\n再决定怎么实现。", desc: "图片能力可以用于产品设计前期：探索风格、生成 UI 草图、修改截图，再交给 Codex 落地。", items: [["01", "概念探索", "同一需求快速生成多种视觉方向"], ["02", "UI 草图", "把用户故事变成首页、看板或移动端方案"], ["03", "方案迭代", "修改颜色、布局、组件和品牌风格"], ["04", "交给 Codex", "选定方向后继续生成真实网站和原型"]] },
  { kind: "usecases", kicker: "07 / OFFICIAL USE CASES", label: "工作流案例", title: "AI 的下一个能力，\n是学会复用。", desc: "OpenAI Use Cases 把真实任务拆成可学习、可复用的工作方式，帮助人和 Agent 一起建立稳定流程。", url: "https://learn.chatgpt.com/use-cases", items: [["01", "从任务出发", "不是罗列功能，而是展示不同工作目标如何被完成。"], ["02", "沉淀方法", "把一次成功的对话整理成可重复的步骤。"], ["03", "连接 Agent", "技能、上下文和工具组合起来，能力才会稳定。"], ["04", "适合借鉴", "从案例中挑一个真实工作流，改成团队自己的版本。"]] },
  { kind: "chain", kicker: "08 / DEEPSEEK HARNESS", label: "Agent 领域的 Laravel", title: "不是拿来用，\n而是拿来构建。", desc: "DeepSeek Harness 基于插件系统，把 Agent 的关键组成拆开，让开发者可以替换、组合和改造。", items: [["01", "Model Adapter", "模型接入", "不同模型可以按需替换"], ["02", "Tool Registry", "工具注册", "把文件、Shell、网页和 API 接进来"], ["03", "Session / Memory", "状态记忆", "保存会话、上下文和历史结论"], ["04", "Agent Loop", "运行循环", "连 Agent 怎么思考和推进都可以改"]] },
  { kind: "cards", kicker: "09 / EVERYTHING IS A PLUGIN", label: "为什么值得研究", title: "从使用 Agent，\n到构建 Agent。", desc: "它让 Agent 的内部结构变得可见、可改、可重组，但灵活性也带来更高的工程复杂度。", items: [["01", "可见", "把模型、工具、会话和 Agent Loop 显性化"], ["02", "可替换", "不必把模型和工具能力写死在产品里"], ["03", "可组合", "像搭建应用一样按需组装 Agent"], ["04", "有代价", "插件依赖、配置和调试都更复杂"]] },
  { kind: "matrix", kicker: "10 / AGENT ARCHITECTURE", label: "Agent 架构", title: "Agent 不只是模型，\n而是一套工作系统。", desc: "我更喜欢用一家公司来理解 Agent：模型负责专业判断，Runtime 提供组织环境，Harness 负责总协调。", items: [["Model", "高级工程师", "负责理解、推理和生成，但需要组织提供环境与权限"], ["Agent Runtime", "公司运营体系", "管理会话、状态、权限、资源和执行环境"], ["Harness", "集团总办", "拆解目标、调度工具、收集结果并推动循环"], ["Tools", "专业部门 / 外部服务", "读写文件、执行命令、浏览网页和调用 API"], ["Context", "当前项目资料", "需求、代码、规则和任务背景"], ["Memory", "公司档案 / 知识库", "沉淀历史经验、长期规则和项目结论"], ["Workflow", "制度与流程", "规定协作、验收、审批和人工收口"]] },
  { kind: "end", kicker: "11 / MY TAKEAWAY", label: "我的判断", title: "选 Agent 的重点，\n是理解整套架构。", desc: "工具会变化，但模型、Harness、工具、上下文和工作流这几个层次会持续存在。", items: [["日常", "Cursor", "把 Agent 放在编辑器里"], ["能力", "Codex", "GPT + Codex，多生态、多模态，适合复杂任务"], ["弹性", "OpenCode", "保留低成本和可替代性"], ["理解", "Harness / Pi", "研究 Agent 为什么这样工作"]], note: "我的结论 / 不是哪个 Agent 最强，而是哪套架构最适合当前工作。" }
];
const legacyDocsSlides: DeckSlide[] = [
  { kind: "cover", kicker: "PART II / AI PROJECT DOCS", label: "AI 项目文档入口", title: "AI 接手项目，\n先看文档入口。", desc: "真实目录结构 · 真实 Markdown · 逐项讲解" },
  { kind: "cards", kicker: "12 / WHY AN ENTRY POINT", label: "为什么需要入口文档", title: "没有入口，\nAI 会先搞错。", desc: "旧项目往往同时包含现状、历史分析和未来规划。入口文档先把事实和边界讲清楚。", items: [["可能混淆", "Symfony 与 Laravel", "把迁移目标误当成当前实现"], ["可能混淆", "Web / H5 / App / Agent", "多套认证入口，不能套用同一规则"], ["可能混淆", "不同接口响应格式", "旧系统的响应并不统一"], ["入口价值", "先确认，再动代码", "知道读什么、改什么、如何验证"]] },
  { kind: "chain", kicker: "13 / THE DOCUMENT CHAIN", label: "四类资料的关系", title: "四类资料，\n一条导航链。", desc: "不是四份重复说明，而是从兼容入口到正式交付的不同层级。", items: [["01", "AGENTS.md", "兼容入口", "告诉所有 AI 从哪里开始"], ["02", "CLAUDE.md", "项目主规则", "现状、环境、架构和铁律"], ["03", ".claude/", "本地分析库", "清单、风险、上下文和日志"], ["04", "docs/", "正式交付", "需求、测试和部署"]] },
  { kind: "code", kicker: "14 / THE FIRST TWO FILES", label: "入口文件", title: "短入口，\n长上下文。", desc: "入口文件不承担所有细节，只负责把 AI 引导到正确的位置。", blocks: [["AGENTS.md", "# AI 接手入口\n\n统一阅读 CLAUDE.md\n不要全量扫描代码库\n当前是 Symfony 3.3\n改接口前先读风险分析"], ["CLAUDE.md", "# 项目定位\n图书、作业、考试、教师端\n\n## 环境速查\nPHP 5.6.9\nSymfony 3.3.14\nDoctrine ORM"]] },
  { kind: "matrix", kicker: "15 / CURRENT CODE FACTS", label: "项目现状", title: "环境事实，\n决定 AI 怎么写。", desc: "版本、命令和依赖边界，是生成代码和验证方案的前提。", items: [["PHP 5.6.9", "语言 / 版本", "语法必须兼容旧版本"], ["Symfony 3.3.14", "框架", "命令入口是 php bin/console"], ["Doctrine ORM", "数据层", "不能默认套用其它项目习惯"], ["先读文档", "注意事项", "不要默认全量扫描"]] },
  { kind: "route", kicker: "16 / THE HANDOFF LOOP", label: "新任务接手流程", title: "新任务接手，\n按四步收口。", desc: "从入口规则到专题知识，再回到代码和验证，最后把结论留在知识库里。", items: [["01", "读入口", "AGENTS.md / CLAUDE.md", "确认现状和禁区"], ["02", "选专题", ".claude/ 清单、风险和历史", "按任务读取上下文"], ["03", "定位代码", "路由 → Controller → Service", "回到真实实现"], ["04", "验证留痕", "命令、Diff、测试与日志", "把结论留下来"]] },
  { kind: "end", kicker: "17 / QUICK REFERENCE", label: "一页速查", title: "先建立事实，\n再让 AI 动手。", desc: "文档不是 AI 的附属品，而是 AI 进入真实项目时的第一层工程基础设施。", items: [["AGENTS.md", "入口在哪里", "哪些提醒必须先看到"], ["CLAUDE.md", "当前项目是什么", "环境、架构和铁律是什么"], [".claude/", "专题材料在哪里", "接口、风险、规划和历史"], ["docs/", "交付资料在哪里", "需求、测试、部署与团队交付"]] }
];
const docsSlides: DeckSlide[] = documentSlides;
function Title({ slide }: { slide: DeckSlide }) { const lines = slide.title.split("\n"); return <div className="unified-heading"><div><h1>{lines.map((line, index) => <span key={line}>{index > 0 && <br />}<em className={index === lines.length - 1 ? "accent" : ""}>{line}</em></span>)}</h1>{slide.desc && <p>{slide.desc}</p>}</div></div>; }
function SlideBody({ slide }: { slide: DeckSlide }) {
  if (slide.kind === "cover") return <><div className="unified-kicker"><span className="orange-dot" /> {slide.kicker}</div><Title slide={slide} /><div className="cover-graphic"><div>PROJECT<br /><b>MAP</b></div><span>MODEL</span><span>TOOLS</span><span>CONTEXT</span><span>WORKFLOW</span></div><div className="unified-footer"><span>{slide.footer || slide.desc}</span><span>← / → 开始浏览</span></div></>;
  return <><div className="unified-topline"><span>{slide.kicker}</span><span>{slide.label}</span></div><Title slide={slide} />
    {slide.kind === "intro" && <><div className="intro-event">{slide.footer}</div><div className="content-intro">{slide.items?.map(([tag, name, text]) => <article key={tag}><span>{tag}</span><strong>{name}</strong><p>{text}</p></article>)}</div></>}
    {slide.kind === "usecases" && <div className="content-usecases"><article className="usecases-link-card"><span>OFFICIAL RESOURCE / OPENAI</span><strong>ChatGPT<br />Use Cases</strong><p>从分析、写作到研究和编码，看看真实工作流如何被拆解、复用和沉淀。</p><a href={slide.url} target="_blank" rel="noreferrer">打开官方案例 ↗</a></article><div className="usecases-points">{slide.items?.map(([tag, name, text]) => <article key={tag}><span>{tag}</span><strong>{name}</strong><p>{text}</p></article>)}</div></div>}
    {slide.kind === "compare" && <div className="content-compare"><article><h3>{slide.left?.title}</h3><ul>{slide.left?.items.map((item) => <li key={item}>{item}</li>)}</ul></article><article><h3>{slide.right?.title}</h3><ul>{slide.right?.items.map((item) => <li key={item}>{item}</li>)}</ul></article></div>}
    {slide.kind === "cards" && <div className={`content-cards ${slide.cards?.length === 3 ? "three" : ""}`}>{(slide.items || slide.cards)?.map(([tag, name, text]) => <article key={name}><span>{tag}</span><strong>{name}</strong><p>{text}</p></article>)}</div>}
    {slide.kind === "chain" && <div className="content-chain">{slide.items?.map(([number, name, role, text]) => <article key={name}><b>{number}</b><strong>{name}</strong><span>{role}</span><p>{text}</p></article>)}</div>}
    {slide.kind === "matrix" && <div className="content-matrix"><div className="matrix-head"><span>工具 / 事实</span><span>定位</span><span>说明</span></div>{slide.items?.map(([name, role, text]) => <div key={name}><strong>{name}</strong><b>{role}</b><span>{text}</span></div>)}</div>}
    {slide.kind === "facts" && <div className={`content-facts ${slide.items && slide.items.length > 4 ? "five" : ""}`}>{slide.items?.map(([tag, name, text]) => <article key={name}><span>{tag}</span><strong>{name}</strong><p>{text}</p></article>)}</div>}
    {slide.kind === "list" && <div className="content-list">{slide.items?.map(([tag, name, text]) => <div key={name}><b>{tag}</b><strong>{name}</strong><span>{text}</span></div>)}</div>}
    {slide.kind === "route" && <><div className="content-route">{slide.items?.map(([number, name, main, text]) => <div key={number}><b>{number}</b><strong>{name}</strong><span>{main}</span>{text && <small>{text}</small>}</div>)}</div>{slide.url && <a className="route-link" href={slide.url} target="_blank" rel="noreferrer">进入 GPT Sites ↗</a>}</>}
    {slide.kind === "code" && <><div className={`content-code ${slide.blocks?.length === 1 ? "single" : ""}`}>{slide.blocks?.map((block) => { const [tag, name, text] = block.length === 3 ? block : ["", block[0], block[1]]; return <article key={name}><span>{tag}</span><h3>{name}</h3><pre>{text}</pre></article>; })}</div>{slide.items && <div className="content-code-impact">{slide.items.map(([name, text]) => <div key={name}><strong>{name}</strong><span>{text}</span></div>)}</div>}</>}
    {slide.kind === "end" && <><div className="content-cards end-cards">{slide.items?.map((row) => { const [name, role, text] = row; return <article key={name}><span>{name}</span>{text && <strong>{role}</strong>}<p>{text || role}</p></article>; })}</div><div className="end-note">{slide.note || "内容收口 / 先建立当前事实，再按任务取上下文。"}</div></>}
  </>;
}
export default function Home() {
  const [section, setSection] = useState<"agent" | "docs">("agent");
  const [active, setActive] = useState(0);
  const slides = useMemo(() => section === "agent" ? agentSlides : docsSlides, [section]);
  const slide = slides[active];
  const go = (delta: number) => setActive((value) => Math.max(0, Math.min(slides.length - 1, value + delta)));
  const switchSection = (next: "agent" | "docs") => { setSection(next); setActive(0); };
  useEffect(() => { const onKey = (event: KeyboardEvent) => { if (["ArrowRight", "ArrowDown", "PageDown", " "].includes(event.key)) { event.preventDefault(); go(1); } if (["ArrowLeft", "ArrowUp", "PageUp"].includes(event.key)) { event.preventDefault(); go(-1); } if (event.key === "Home") setActive(0); if (event.key === "End") setActive(slides.length - 1); }; window.addEventListener("keydown", onKey); return () => window.removeEventListener("keydown", onKey); }, [slides.length]);
  return <main className={`unified-app ${slide.kind}`}><header className="unified-bar"><a className="unified-brand" href="#slide-1"><span>AI</span><b>项目分享</b></a><nav className="section-nav"><button className={section === "agent" ? "active" : ""} onClick={() => switchSection("agent")}>01 / 我的 Agent 工具栈</button><button className={section === "docs" ? "active" : ""} onClick={() => switchSection("docs")}>02 / AI 接手真实项目</button></nav><div className="unified-counter"><span>{String(active + 1).padStart(2, "0")}</span><i>/</i>{String(slides.length).padStart(2, "0")}</div></header><section className="unified-stage"><div className="unified-slide"><SlideBody slide={slide} /></div></section><footer className="unified-controls"><div className="progress-track"><span style={{ width: `${((active + 1) / slides.length) * 100}%` }} /></div><div className="dot-nav">{slides.map((_, index) => <button key={index} className={active === index ? "active" : ""} onClick={() => setActive(index)} aria-label={`第 ${index + 1} 页`} />)}</div><div className="nav-buttons"><button onClick={() => go(-1)} disabled={active === 0} aria-label="上一页">←</button><button onClick={() => go(1)} disabled={active === slides.length - 1} aria-label="下一页">→</button></div></footer></main>;
}
